

version: '3.8'

services:
  sprinkler-api:
    image: ${IMAGE_URL}
    build:
      context: .
      args:
        - GOOGLE_APPLICATION_CREDENTIALS
        - DEBUG
        - LOGS
        - LOCAL_PORT
        - ROUTE_BASE
        - SERVICE
        - EXECUTABLE
        - TZ
    container_name: ${CONTAINER}
    restart: unless-stopped
    env_file:
        - ".env.local.yml"
    volumes:
        - ".secrets:/secrets"
    ports:
      - "0.0.0.0:${TARGET_LOCAL_PORT}:8080"
